---
title: "hw5_vy2196"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

```

### Problem 1

```{r}
# Function to check if at least two people share a birthday
share_birthday = function(n) {
  birthdays = sample(1:365, n, replace = TRUE)  # randomly assign birthdays
  return(length(unique(birthdays)) < n)          
}

set.seed(1)
n_sim = 10000 # number of simulations per group size

group_sizes = 2:50
prob_shared = numeric(length(group_sizes))

for (i in seq_along(group_sizes)) {
  n = group_sizes[i]
  results = replicate(n_sim, share_birthday(n))
  prob_shared[i] = mean(results)   # proportion of TRUE results
}
```

```{r}
#making a plot
sim_results = tibble(
  n = 2:50,
  prob = map_dbl(n, ~ mean(replicate(10000, share_birthday(.x))))
)

ggplot(sim_results, aes(x = n, y = prob)) +
  geom_line(color = "blue") +
  geom_point(color = "darkblue") +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "red") +
  labs(title = "Probability of Shared Birthday vs Group Size",
       x = "Group Size",
       y = "Probability of Shared Birthday") +
  theme_minimal()
```
The probability is around 50% when the group size is about 23 people, and it reaches 100% when the group size is about 50 people.

### Problem 2

```{r}
library(broom)

n = 30
sigma = 5
mu_values = 0:6
n_sim = 5000

simulate_ttest = function(mu, n = 30, sigma = 5) {
  x = rnorm(n, mean = mu, sd = sigma)
  t_res = t.test(x, mu = 0)
  
  # Clean the t-test output using broom::tidy
  broom::tidy(t_res) |>
    select(estimate, p.value) |>  # keep only needed columns
    mutate(true_mu = mu)}


# Run simulations for each mu
sim_results = map_df(mu_values, function(mu) {
  replicate(n_sim, simulate_ttest(mu, n, sigma), simplify = FALSE) |>
    bind_rows()})

```

